@ ----- Delta Emerald ----- @

	.align 2
Cry_Pikachu_Battle::
	.incbin "sound/delta_samples/cries/pikachu_battle.bin"

	.align 2
Cry_Pikachu_Faint::
	.incbin "sound/delta_samples/cries/pikachu_faint.bin"

	.align 2
Cry_Eevee_Battle::
	.incbin "sound/delta_samples/cries/eevee_battle.bin"

	.align 2
Cry_Eevee_Faint::
	.incbin "sound/delta_samples/cries/eevee_faint.bin"

	.align 2
MEME_MiraculousLadybug::
	.incbin "sound/delta_samples/cries/that_one_french_ladybug.bin"

	.align 2
MEME_AMOGUS::
	.incbin "sound/delta_samples/cries/sus.bin"

	.align 2
MEME_OP::
	.incbin "sound/delta_samples/cries/op.bin"

@ ----- Delta - UI SFX ----- @

	.align 2
Delta_SE_ChooseMenuItem::
	.incbin "sound/delta_samples/sg_se_select.bin"

	.align 2
Delta_SE_SelectMenuItem::
	.incbin "sound/delta_samples/se_choose.bin"

	.align 2
Delta_SE_Complete::
	.incbin "sound/delta_samples/se_complete.bin"

	.align 2
Delta_SE_XY_CANCEL1::
	.incbin "sound/delta_samples/se_xy_cancel1.bin"

	.align 2
Delta_SE_XY_DECIDE1::
	.incbin "sound/delta_samples/se_xy_decide1.bin"

	.align 2
Delta_SE_XY_PAGE3::
	.incbin "sound/delta_samples/se_xy_page3.bin"

@ ----- Delta - ORAS Instruments ----- @

	.align 2
DeltaMus_stylusrmx_crash_cymbal::
	.incbin "sound/delta_samples/stylusrmx_crash_cymbal.bin"

	.align 2
DeltaMus_stylusrmx_kick::
	.incbin "sound/delta_samples/stylusrmx_kick.bin"

	.align 2
DeltaMus_stylusrmx_snare::
	.incbin "sound/delta_samples/stylusrmx_snare.bin"

	.align 2
DeltaMus_ad2_close_hihat::
	.incbin "sound/delta_samples/ad2_close_hihat.bin"

	.align 2
DeltaMus_ad2_open_hihat::
	.incbin "sound/delta_samples/ad2_open_hihat.bin"

	.align 2
DeltaMus_ad2_crash_sabian_aax::
	.incbin "sound/delta_samples/ad2_crash_sabian_aax.bin"

	.align 2
DeltaMus_ad2_crash_sabian_vault::
	.incbin "sound/delta_samples/ad2_crash_sabian_vault.bin"

	.align 2
DeltaMus_ad2_pearl_snare::
	.incbin "sound/delta_samples/ad2_pearl_snare.bin"

	.align 2
DeltaMus_ad2_ride_sabian_hhx::
	.incbin "sound/delta_samples/ad2_ride_sabian_hhx.bin"

	.align 2
DeltaMus_ewqlso_18_german_cymbal::
	.incbin "sound/delta_samples/ewqlso_18_german_cymbal.bin"

	.align 2
DeltaMus_ewqlso_19_french_cymbal::
	.incbin "sound/delta_samples/ewqlso_19_french_cymbal.bin"

	.align 2
DeltaMus_ewqlso_22_cymbal_swell::
	.incbin "sound/delta_samples/ewqlso_22_cymbal_swell.bin"

	.align 2
DeltaMus_ewqlso_bassdrum::
	.incbin "sound/delta_samples/ewqlso_bassdrum.bin"

	.align 2
DeltaMus_ewqlso_orch_chimes_60::
	.incbin "sound/delta_samples/ewqlso_orch_chimes_60.bin"

	.align 2
DeltaMus_ewqlso_orch_chimes_72::
	.incbin "sound/delta_samples/ewqlso_orch_chimes_72.bin"

	.align 2
DeltaMus_ewqlso_timpani::
	.incbin "sound/delta_samples/ewqlso_timpani.bin"

	.align 2
DeltaMus_ewqlso_snare_ens_small::
	.incbin "sound/delta_samples/ewqlso_snare_ens_small.bin"

	.align 2
DeltaMus_stylusrmx_halfmoon_hit1::
	.incbin "sound/delta_samples/stylusrmx_halfmoon_hit1.bin"

	.align 2
DeltaMus_stylusrmx_halfmoon_hit2::
	.incbin "sound/delta_samples/stylusrmx_halfmoon_hit2.bin"

	.align 2
DeltaMus_halion_gaga_saw::
	.incbin "sound/delta_samples/halion_gaga_saw.bin"

	.align 2
DeltaMus_halion_3_osc_fooling::
	.incbin "sound/delta_samples/halion_3_osc_fooling.bin"

	.align 2
DeltaMus_ewqlso_4tp_52::
	.incbin "sound/delta_samples/ewqlso_4tp_52.bin"

	.align 2
DeltaMus_ewqlso_4tp_55::
	.incbin "sound/delta_samples/ewqlso_4tp_55.bin"

	.align 2
DeltaMus_ewqlso_4tp_60::
	.incbin "sound/delta_samples/ewqlso_4tp_60.bin"

	.align 2
DeltaMus_ewqlso_4tp_64::
	.incbin "sound/delta_samples/ewqlso_4tp_64.bin"

	.align 2
DeltaMus_ewqlso_4tp_67::
	.incbin "sound/delta_samples/ewqlso_4tp_67.bin"

	.align 2
DeltaMus_ewqlso_4tp_71::
	.incbin "sound/delta_samples/ewqlso_4tp_71.bin"

	.align 2
DeltaMus_ewqlso_4tp_75::
	.incbin "sound/delta_samples/ewqlso_4tp_75.bin"

	.align 2
DeltaMus_ewqlso_4tp_77::
	.incbin "sound/delta_samples/ewqlso_4tp_77.bin"

	.align 2
DeltaMus_ewqlso_6horns_60::
	.incbin "sound/delta_samples/ewqlso_6horns_60.bin"

	.align 2
DeltaMus_ewqlso_6horns_72::
	.incbin "sound/delta_samples/ewqlso_6horns_72.bin"

	.align 2
DeltaMus_trilian_fenderbass::
	.incbin "sound/delta_samples/trilian_fenderbass.bin"

	.align 2
DeltaMus_trilian_acousticbass::
	.incbin "sound/delta_samples/trilian_acbass_48.bin"

	.align 2
DeltaMus_ewqlso_4tb_28::
	.incbin "sound/delta_samples/ewqlso_4tb_28.bin"

	.align 2
DeltaMus_ewqlso_4tb_33::
	.incbin "sound/delta_samples/ewqlso_4tb_33.bin"

	.align 2
DeltaMus_ewqlso_4tb_40::
	.incbin "sound/delta_samples/ewqlso_4tb_40.bin"

	.align 2
DeltaMus_ewqlso_4tb_46::
	.incbin "sound/delta_samples/ewqlso_4tb_46.bin"

	.align 2
DeltaMus_ewqlso_4tb_51::
	.incbin "sound/delta_samples/ewqlso_4tb_51.bin"

	.align 2
DeltaMus_ewqlso_4tb_56::
	.incbin "sound/delta_samples/ewqlso_4tb_56.bin"

	.align 2
DeltaMus_ewqlso_4tb_60::
	.incbin "sound/delta_samples/ewqlso_4tb_60.bin"

	.align 2
DeltaMus_ewqlso_4tb_65::
	.incbin "sound/delta_samples/ewqlso_4tb_65.bin"

	.align 2
DeltaMus_ewqlso_6horns_adv_48::
	.incbin "sound/delta_samples/ewqlso_6horns_adv_48.bin"

	.align 2
DeltaMus_ewqlso_6horns_adv_55::
	.incbin "sound/delta_samples/ewqlso_6horns_adv_55.bin"

	.align 2
DeltaMus_ewqlso_6horns_adv_60::
	.incbin "sound/delta_samples/ewqlso_6horns_adv_60.bin"

	.align 2
DeltaMus_ewqlso_6horns_adv_67::
	.incbin "sound/delta_samples/ewqlso_6horns_adv_67.bin"

	.align 2
DeltaMus_ewqlso_6horns_adv_72::
	.incbin "sound/delta_samples/ewqlso_6horns_adv_72.bin"

	.align 2
DeltaMus_halion_electric_piano_48::
	.incbin "sound/delta_samples/halion_electric_piano_48.bin"

	.align 2
DeltaMus_halion_electric_piano_60::
	.incbin "sound/delta_samples/halion_electric_piano_60.bin"

	.align 2
DeltaMus_halion_electric_piano_72::
	.incbin "sound/delta_samples/halion_electric_piano_72.bin"

	.align 2
DeltaMus_halion_electric_piano_84::
	.incbin "sound/delta_samples/halion_electric_piano_84.bin"

	.align 2
DeltaMus_omnisphere_wendybell::
	.incbin "sound/delta_samples/omnisphere_wendybell.bin"

	.align 2
DeltaMus_temp_oboe::
	.incbin "sound/delta_samples/temp_sc88pro_oboe.bin"

	.align 2
DeltaMus_ad1_startup_kick::
	.incbin "sound/delta_samples/ad1_startup_kick.bin"

	.align 2
DeltaMus_ad1_startup_snare::
	.incbin "sound/delta_samples/ad1_startup_snare.bin"

	.align 2
DeltaMus_ad1_startup_crash1::
	.incbin "sound/delta_samples/ad1_startup_crash1.bin"

	.align 2
DeltaMus_ad1_startup_closehat::
	.incbin "sound/delta_samples/ad1_startup_closehat.bin"

	.align 2
DeltaMus_ad1_startup_openhat::
	.incbin "sound/delta_samples/ad1_startup_openhat.bin"

	.align 2
DeltaMus_korg_attack_brasses_60::
	.incbin "sound/delta_samples/korg_attack_brasses_60.bin"

	.align 2
DeltaMus_korg_attack_brasses_72::
	.incbin "sound/delta_samples/korg_attack_brasses_72.bin"

	.align 2
DeltaMus_korg_attack_brasses_84::
	.incbin "sound/delta_samples/korg_attack_brasses_84.bin"

	.align 2
DeltaMus_sc88pro_60sorgan::
	.incbin "sound/delta_samples/sc88pro_60sorgan.bin"

	.align 2
DeltaMus_korg_volca_cymbal::
	.incbin "sound/delta_samples/korg_volca_cymbal.bin"

	.align 2
DeltaMus_korg_volca_openhat::
	.incbin "sound/delta_samples/korg_volca_openhat.bin"

	.align 2
DeltaMus_korg_volca_closehat::
	.incbin "sound/delta_samples/korg_volca_closehat.bin"

	.align 2
DeltaMus_korg_volca_snare::
	.incbin "sound/delta_samples/korg_volca_snare.bin"

	.align 2
DeltaMus_korg_volca_kick::
	.incbin "sound/delta_samples/korg_volca_kick.bin"

	.align 2
DeltaMus_korg_volca_tamb::
	.incbin "sound/delta_samples/korg_volca_tamb.bin"

	.align 2
DeltaMus_halion_gm_closehat::
	.incbin "sound/delta_samples/halion_gm_closehat.bin"

	.align 2
DeltaMus_halion_gm_snare::
	.incbin "sound/delta_samples/halion_gm_snare.bin"

	.align 2
DeltaMus_halion_gm_kick::
	.incbin "sound/delta_samples/halion_gm_kick.bin"

	.align 2
DeltaMus_halion_gm_cymbal::
	.incbin "sound/delta_samples/halion_gm_cymbal.bin"

	.align 2
DeltaMus_halion_brass_sect_84::
	.incbin "sound/delta_samples/halion_brass_sect_84.bin"

	.align 2
DeltaMus_halion_brass_sect_72::
	.incbin "sound/delta_samples/halion_brass_sect_72.bin"

	.align 2
DeltaMus_halion_brass_sect_60::
	.incbin "sound/delta_samples/halion_brass_sect_60.bin"

	.align 2
DeltaMus_halion_slap_bass::
	.incbin "sound/delta_samples/halion_slap_bass.bin"

	.align 2
DeltaMus_halion_arctic_bells_84::
	.incbin "sound/delta_samples/halion_arctic_bells_84.bin"

	.align 2
DeltaMus_halion_arctic_bells_72::
	.incbin "sound/delta_samples/halion_arctic_bells_72.bin"

	.align 2
DeltaMus_halion_arctic_bells_60::
	.incbin "sound/delta_samples/halion_arctic_bells_60.bin"

	.align 2
DeltaMus_halion_finestlead_84::
	.incbin "sound/delta_samples/halion_finestlead_84.bin"

	.align 2
DeltaMus_halion_finestlead_72::
	.incbin "sound/delta_samples/halion_finestlead_72.bin"

	.align 2
DeltaMus_halion_finestlead_60::
	.incbin "sound/delta_samples/halion_finestlead_60.bin"



@ ----- Delta - Stylus RMX Loops ----- @

@ ----- 120 Notre Dame ----- @

	.align 2
DeltaMus_stylusrmx_120nd_01::
	.incbin "sound/delta_samples/stylus_loops/120notredame/01.bin"

	.align 2
DeltaMus_stylusrmx_120nd_02::
	.incbin "sound/delta_samples/stylus_loops/120notredame/02.bin"

	.align 2
DeltaMus_stylusrmx_120nd_03::
	.incbin "sound/delta_samples/stylus_loops/120notredame/03.bin"

	.align 2
DeltaMus_stylusrmx_120nd_04::
	.incbin "sound/delta_samples/stylus_loops/120notredame/04.bin"

	.align 2
DeltaMus_stylusrmx_120nd_05::
	.incbin "sound/delta_samples/stylus_loops/120notredame/05.bin"

	.align 2
DeltaMus_stylusrmx_120nd_06::
	.incbin "sound/delta_samples/stylus_loops/120notredame/06.bin"

	.align 2
DeltaMus_stylusrmx_120nd_07::
	.incbin "sound/delta_samples/stylus_loops/120notredame/07.bin"

	.align 2
DeltaMus_stylusrmx_120nd_08::
	.incbin "sound/delta_samples/stylus_loops/120notredame/08.bin"

	.align 2
DeltaMus_stylusrmx_120nd_09::
	.incbin "sound/delta_samples/stylus_loops/120notredame/09.bin"

	.align 2
DeltaMus_stylusrmx_120nd_10::
	.incbin "sound/delta_samples/stylus_loops/120notredame/10.bin"

	.align 2
DeltaMus_stylusrmx_120nd_11::
	.incbin "sound/delta_samples/stylus_loops/120notredame/11.bin"

	.align 2
DeltaMus_stylusrmx_120nd_12::
	.incbin "sound/delta_samples/stylus_loops/120notredame/12.bin"

	.align 2
DeltaMus_stylusrmx_120nd_13::
	.incbin "sound/delta_samples/stylus_loops/120notredame/13.bin"

	.align 2
DeltaMus_stylusrmx_120nd_14::
	.incbin "sound/delta_samples/stylus_loops/120notredame/14.bin"

	.align 2
DeltaMus_stylusrmx_120nd_15::
	.incbin "sound/delta_samples/stylus_loops/120notredame/15.bin"

	.align 2
DeltaMus_stylusrmx_120nd_16::
	.incbin "sound/delta_samples/stylus_loops/120notredame/16.bin"

@ ----- 79 Bossa Luv ----- @

	.align 2
DeltaMus_stylusrmx_79bl_rim::
	.incbin "sound/delta_samples/stylus_loops/79bossaluv/rim.bin"

	.align 2
DeltaMus_stylusrmx_79bl_snare::
	.incbin "sound/delta_samples/stylus_loops/79bossaluv/snare.bin"

