	.align 2
voicegroup269::
	voice_directsound 60, 0, DeltaMus_ewqlso_6horns_adv_48, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_6horns_adv_48, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_6horns_adv_48, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_6horns_adv_55, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_6horns_adv_60, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_6horns_adv_67, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_6horns_adv_72, 255, 0, 255, 220

