	.align 2
voicegroup265::
	voice_directsound 60, 0, DeltaMus_ewqlso_4tp_52, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tp_55, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tp_60, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tp_64, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tp_67, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tp_71, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tp_75, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tp_77, 255, 0, 255, 220
