	.align 2
voicegroup268::
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_01, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_02, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_03, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_04, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_05, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_06, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_07, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_08, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_09, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_10, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_11, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_12, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_13, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_14, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_15, 255, 245, 0, 245
	voice_directsound_no_resample 60, 72, DeltaMus_stylusrmx_120nd_16, 255, 245, 0, 245

