	.align 2
voicegroup267::
	voice_directsound 60, 0, DeltaMus_ewqlso_4tb_28, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tb_33, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tb_40, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tb_46, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tb_51, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tb_56, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tb_60, 255, 0, 255, 220
	voice_directsound 60, 0, DeltaMus_ewqlso_4tb_65, 255, 0, 255, 220

